import { HoraAgendamento } from "../horaagendamento"

const horasAgendamento: HoraAgendamento[] = [
    {
        id: 1,        
        horario: '06:00',
        periodoDia: 'Manhã',
        ativo: false,
    },
    {
        id: 2,        
        horario: '06:15',
        periodoDia: 'Manhã',
        ativo: false,
    },
    {
        id: 3,        
        horario: '06:30',
        periodoDia: 'Manhã',
        ativo: false,
    },
    {
        id: 4,        
        horario: '06:45',
        periodoDia: 'Manhã',
        ativo: false,
    },    
    {
        id: 5,        
        horario: '07:00',
        periodoDia: 'Manhã',
        ativo: false,
    },
    {
        id: 6,        
        horario: '07:15',
        periodoDia: 'Manhã',
        ativo: false,
    },
    {
        id: 7,        
        horario: '07:30',
        periodoDia: 'Manhã',
        ativo: false,
    },
    {
        id: 8,        
        horario: '07:45',
        periodoDia: 'Manhã',
        ativo: false,
    },    
    {
        id: 9,        
        horario: '08:00',
        periodoDia: 'Manhã',
        ativo: true,
    },
    {
        id: 10,        
        horario: '08:15',
        periodoDia: 'Manhã',
        ativo: true,
    },
    {
        id: 11,        
        horario: '08:30',
        periodoDia: 'Manhã',
        ativo: true,
    },
    {
        id: 12,        
        horario: '08:45',
        periodoDia: 'Manhã',
        ativo: true,
    },
    {
        id: 13,        
        horario: '09:00',
        periodoDia: 'Manhã',
        ativo: true,
    },
    {
        id: 14,        
        horario: '09:15',
        periodoDia: 'Manhã',
        ativo: true,
    },
    {
        id: 15,        
        horario: '09:30',
        periodoDia: 'Manhã',
        ativo: true,
    },
    {
        id: 16,        
        horario: '09:45',
        periodoDia: 'Manhã',
        ativo: true,
    },
    {
        id: 17,        
        horario: '10:00',
        periodoDia: 'Manhã',
        ativo: true,
    },
    {
        id: 18,        
        horario: '10:15',
        periodoDia: 'Manhã',
        ativo: true,
    },
    {
        id: 19,        
        horario: '10:30',
        periodoDia: 'Manhã',
        ativo: true,
    },
    {
        id: 20,        
        horario: '10:45',
        periodoDia: 'Manhã',
        ativo: true,
    },
    {
        id: 21,        
        horario: '11:00',
        periodoDia: 'Manhã',
        ativo: true,
    },
    {
        id: 22,        
        horario: '11:15',
        periodoDia: 'Manhã',
        ativo: true,
    },
    {
        id: 23,        
        horario: '11:30',
        periodoDia: 'Manhã',
        ativo: true,
    },
    {
        id: 24,        
        horario: '11:45',
        periodoDia: 'Manhã',
        ativo: true,
    },    
    {
        id: 25,        
        horario: '12:00',
        periodoDia: 'Tarde',
        ativo: false,
    },
    {
        id: 26,        
        horario: '12:15',
        periodoDia: 'Tarde',
        ativo: false,
    },
    {
        id: 27,        
        horario: '12:30',
        periodoDia: 'Tarde',
        ativo: false,
    },
    {
        id: 28,        
        horario: '12:45',
        periodoDia: 'Tarde',
        ativo: false,
    },    
    {
        id: 29,        
        horario: '13:00',
        periodoDia: 'Tarde',
        ativo: true,
    },
    {
        id: 30,        
        horario: '13:15',
        periodoDia: 'Tarde',
        ativo: true,
    },
    {
        id: 31,        
        horario: '13:30',
        periodoDia: 'Tarde',
        ativo: true,
    },
    {
        id: 32,        
        horario: '13:45',
        periodoDia: 'Tarde',
        ativo: true,
    },
    {
        id: 33,        
        horario: '14:00',
        periodoDia: 'Tarde',
        ativo: true,
    },
    {
        id: 34,        
        horario: '14:15',
        periodoDia: 'Tarde',
        ativo: true,
    },
    {
        id: 35,        
        horario: '14:30',
        periodoDia: 'Tarde',
        ativo: true,
    },
    {
        id: 36,        
        horario: '14:45',
        periodoDia: 'Tarde',
        ativo: true,
    },
    {
        id: 37,        
        horario: '15:00',
        periodoDia: 'Tarde',
        ativo: true,
    },
    {
        id: 38,        
        horario: '15:15',
        periodoDia: 'Tarde',
        ativo: true,
    },
    {
        id: 39,        
        horario: '15:30',
        periodoDia: 'Tarde',
        ativo: true,
    },
    {
        id: 40,        
        horario: '15:45',
        periodoDia: 'Tarde',
        ativo: true,
    },
    {
        id: 41,        
        horario: '16:00',
        periodoDia: 'Tarde',
        ativo: true,
    },
    {
        id: 42,        
        horario: '16:15',
        periodoDia: 'Tarde',
        ativo: true,
    },
    {
        id: 43,        
        horario: '16:30',
        periodoDia: 'Tarde',
        ativo: true,
    },
    {
        id: 44,        
        horario: '16:45',
        periodoDia: 'Tarde',
        ativo: true,
    },
    {
        id: 45,        
        horario: '17:00',
        periodoDia: 'Tarde',
        ativo: true,
    },
    {
        id: 46,        
        horario: '17:15',
        periodoDia: 'Tarde',
        ativo: true,
    },
    {
        id: 47,        
        horario: '17:30',
        periodoDia: 'Tarde',
        ativo: true,
    },
    {
        id: 48,        
        horario: '17:45',
        periodoDia: 'Tarde',
        ativo: true,
    },
    {
        id: 49,        
        horario: '18:00',
        periodoDia: 'Noite',
        ativo: true,
    },
    {
        id: 50,        
        horario: '18:15',
        periodoDia: 'Noite',
        ativo: true,
    },
    {
        id: 51,        
        horario: '18:30',
        periodoDia: 'Noite',
        ativo: true,
    },
    {
        id: 52,        
        horario: '18:45',
        periodoDia: 'Noite',
        ativo: true,
    },
    {
        id: 53,        
        horario: '19:00',
        periodoDia: 'Noite',
        ativo: true,
    },
    {
        id: 54,        
        horario: '19:15',
        periodoDia: 'Noite',
        ativo: true,
    },
    {
        id: 55,        
        horario: '19:30',
        periodoDia: 'Noite',
        ativo: true,
    },
    {
        id: 56,        
        horario: '19:45',
        periodoDia: 'Noite',
        ativo: true,
    },
    {
        id: 57,        
        horario: '20:00',
        periodoDia: 'Noite',
        ativo: true,
    },
    {
        id: 58,        
        horario: '20:15',
        periodoDia: 'Noite',
        ativo: true,
    },
    {
        id: 59,        
        horario: '20:30',
        periodoDia: 'Noite',
        ativo: true,
    },
    {
        id: 60,        
        horario: '20:45',
        periodoDia: 'Noite',
        ativo: true,
    },
    {
        id: 61,        
        horario: '21:00',
        periodoDia: 'Noite',
        ativo: true,
    },
    {
        id: 62,        
        horario: '21:15',
        periodoDia: 'Noite',
        ativo: true,
    },
    {
        id: 63,        
        horario: '21:30',
        periodoDia: 'Noite',
        ativo: true,
    },
    {
        id: 64,        
        horario: '21:45',
        periodoDia: 'Noite',
        ativo: true,
    },
    {
        id: 65,        
        horario: '22:00',
        periodoDia: 'Noite',
        ativo: false,
    },
    {
        id: 66,        
        horario: '22:15',
        periodoDia: 'Noite',
        ativo: false,
    },
    {
        id: 67,        
        horario: '22:30',
        periodoDia: 'Noite',
        ativo: false,
    },
    {
        id: 68,        
        horario: '22:45',
        periodoDia: 'Noite',
        ativo: false,
    },
    {
        id: 69,        
        horario: '23:00',
        periodoDia: 'Noite',
        ativo: false,
    },
    {
        id: 70,        
        horario: '23:15',
        periodoDia: 'Noite',
        ativo: false,
    },
    {
        id: 71,        
        horario: '23:30',
        periodoDia: 'Noite',
        ativo: false,
    },
    {
        id: 72,        
        horario: '23:45',
        periodoDia: 'Noite',
        ativo: false,
    },
]

export default horasAgendamento
