GET http://localhost:4000/ping

###
POST http://localhost:4000/auth/

###
POST http://localhost:4000/auth/registrar
content-type: application/json

{
    "nome": "Rebeca Pereira Silva",
    "email": "rebeca@zmail.com",
    "senha": "#Senha123",
    "telefone": "(11) 88888-9999",
    "barbeiro": false
}

###
POST http://localhost:4000/usuario/login
content-type: application/json

{
    "email": "cpc@zmail.com",
    "senha": "#Senha123"
}

###
GET http://localhost:4000/profissionais

###
GET http://localhost:4000/servicos

###
POST http://localhost:4000/agendamentos
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NCwibm9tZSI6IlJlYmVjYSBQZXJlaXJhIFNpbHZhIiwiZW1haWwiOiJyZWJlY2FAem1haWwuY29tIiwidGVsZWZvbmUiOiIoMTEpIDg4ODg4LTk5OTkiLCJiYXJiZWlybyI6ZmFsc2UsImlhdCI6MTczMzIyMjE4NCwiZXhwIjoxNzMzMzA4NTg0fQ.MD7m3D2HfSSCsdnKApa0HWGKspk_YjYRjuoO58C3BtU
Content-Type: application/json

{
    "data": "2024-12-03T13:00:00.000Z",
    "usuario": { "id": 4 },
    "profissional": { "id": 1 },
    "servicos": [
        { "id": 1 },
        { "id": 2 },
        { "id": 3 }
    ]
}

###
GET http://localhost:4000/agendamentos
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NCwibm9tZSI6IlJlYmVjYSBQZXJlaXJhIFNpbHZhIiwiZW1haWwiOiJyZWJlY2FAem1haWwuY29tIiwidGVsZWZvbmUiOiIoMTEpIDg4ODg4LTk5OTkiLCJiYXJiZWlybyI6ZmFsc2UsImlhdCI6MTczMzIyMjE4NCwiZXhwIjoxNzMzMzA4NTg0fQ.MD7m3D2HfSSCsdnKApa0HWGKspk_YjYRjuoO58C3BtU

###
GET http://localhost:4000/agendamentos/1/2024-12-03
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NCwibm9tZSI6IlJlYmVjYSBQZXJlaXJhIFNpbHZhIiwiZW1haWwiOiJyZWJlY2FAem1haWwuY29tIiwidGVsZWZvbmUiOiIoMTEpIDg4ODg4LTk5OTkiLCJiYXJiZWlybyI6ZmFsc2UsImlhdCI6MTczMzIyMjE4NCwiZXhwIjoxNzMzMzA4NTg0fQ.MD7m3D2HfSSCsdnKApa0HWGKspk_YjYRjuoO58C3BtU

###
DELETE http://localhost:4000/agendamentos/2
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NCwibm9tZSI6IlJlYmVjYSBQZXJlaXJhIFNpbHZhIiwiZW1haWwiOiJyZWJlY2FAem1haWwuY29tIiwidGVsZWZvbmUiOiIoMTEpIDg4ODg4LTk5OTkiLCJiYXJiZWlybyI6ZmFsc2UsImlhdCI6MTczMzIyMjE4NCwiZXhwIjoxNzMzMzA4NTg0fQ.MD7m3D2HfSSCsdnKApa0HWGKspk_YjYRjuoO58C3BtU

###
GET http://localhost:4000/agendamentos/ocupacao/2/2024-12-03
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NCwibm9tZSI6IlJlYmVjYSBQZXJlaXJhIFNpbHZhIiwiZW1haWwiOiJyZWJlY2FAem1haWwuY29tIiwidGVsZWZvbmUiOiIoMTEpIDg4ODg4LTk5OTkiLCJiYXJiZWlybyI6ZmFsc2UsImlhdCI6MTczMzIyMjE4NCwiZXhwIjoxNzMzMzA4NTg0fQ.MD7m3D2HfSSCsdnKApa0HWGKspk_YjYRjuoO58C3BtU