const ErrosTraduzidos = {    
    DESCONHECIDO: 'DESCONHECIDO',    
    EMAIL_INVALIDO: 'EMAIL_INVALIDO',
    ID_INVALIDO: 'ID_INVALIDO',
    NOME_CARACTERES_INVALIDOS: 'NOME_CARACTERES_INVALIDOS',
    NOME_GRANDE: 'NOME_GRANDE',
    NOME_PEQUENO: 'NOME_PEQUENO',
    NOME_SEM_SOBRENOME: 'NOME_SEM_SOBRENOME',
    NOME_VAZIO: 'NOME_VAZIO',    
    SENHA_FRACA: 'SENHA_FRACA',
    SENHA_HASH_INVALIDA: 'SENHA_HASH_INVALIDA',
    CPF_INVALIDO: 'CPF_INVALIDO',
    USUARIO_NAO_ENCONTRADO: 'USUARIO_NAO_ENCONTRADO',
    SENHA_INCORRETA: 'SENHA_INCORRETA',
    USUARIO_EMAIL_EXISTENTE: 'USUARIO_EMAIL_EXISTENTE',
} as const

export default ErrosTraduzidos
